name: badproject
on: 
    push:
    branches:
      - "*"
  workflow_dispatch:
env: 
  POSTGRES_DB: badproject
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install 
          npx knex migrate:latest --env test
          npx jest
