name: badproject
on: 
    push:
        branches:
            - "*"
    workflow_dispatch:
  
env: 
     DB_NAME: badproject
     DB_USER: postgres
     DB_PASSWORD: postgres
     POSTGRES_HOST: postgres
     POSTGRES_PORT: 5432
     SESSION_SECRET: fhffjgjhdghdgh

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_USER: ${{env.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
            - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install 
          npx knex migrate:latest
          npx jest
