name: badproject
on: 
    push:
        branches:
            - "*"
    workflow_dispatch:
  
env: 
  POSTGRES_DB: badproject
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
          POSTGRES_HOST: postgres
          SESSION_SECRET: fhffjgjhdghdgh
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install 
          npx knex migrate:latest --env test
          npx jest
