name: badproject
on: 
    push:
        branches:
            - "*"
    workflow_dispatch:
  
env: 
     DB_NAME: badproject
     DB_USER: postgres
     DB_PASSWORD: postgres
     POSTGRES_HOST: postgres
     SESSION_SECRET: fhffjgjhdghdgh

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          DB_NAME: ${{env.DB_NAME}}
          DB_USER: postgres
          DB_PASSWORD: ${{env.DB_PASSWORD}}
          POSTGRES_HOST: postgres
          SESSION_SECRET: fhffjgjhdghdgh
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install 
          npx knex migrate:latest --env development
          npx jest
